alter table if exists "public"."negocio"
add column if not exists "descripcion" character varying(1000);

create table if not exists "public"."negocio_imagenes" (
    "id_imagen" integer generated by default as identity not null,
    "id_negocio" integer not null,
    "url" character varying(500) not null,
    "es_portada" boolean not null default false,
    "orden" integer not null default 0,
    constraint "negocio_imagenes_pkey" primary key ("id_imagen"),
    constraint "fk_negocio_imagenes_negocio" foreign key ("id_negocio")
        references "public"."negocio" ("id_negocio")
        on delete cascade
);

create index if not exists "idx_negocio_imagenes_id_negocio_orden"
on "public"."negocio_imagenes" ("id_negocio", "orden");
